language: python
python:
- 3.5
before_install:
- openssl aes-256-cbc -K $encrypted_5c59e1ea750c_key -iv $encrypted_5c59e1ea750c_iv
  -in travis_ssh_key.enc -out travis_ssh_key -d
- cp travis_ssh_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g resume-cli
script:
- pushd nx6_cv && python setup.py install && popd
- git checkout -b gh-pages origin/gh-pages && nx6-cv build -o "" && git commit -m "Updating CV" -a && git push origin gh-pages
