language: python
python:
- 3.5
before_install:
- openssl aes-256-cbc -K $encrypted_40a60c5bd425_key -iv $encrypted_40a60c5bd425_iv -in travis_ssh_key_new.enc -out travis_ssh_key_new -d
- cp travis_ssh_key_new ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g resume-cli
- apt-get install texlive-full
script:
- pip install .
- git fetch git@github.com:cscutcher/cv.git gh-pages && git checkout -b gh-pages FETCH_HEAD && nx6-cv build -o "" && git commit -m "Updating CV" -a && git push origin gh-pages
